### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#101]
currently "Copyright 2021 Openscapes. All rights reserved." https://github.com/Openscapes/kyber/blob/main/LICENSE

**Comment by stefaniebutland** [comment]
@seankross What's your preference for a license for Kyber? Is MIT ok with you? Let us know and @ateucher offered to do the leg work to make it so

**Comment by seankross** [comment]
MIT works for me.

**Comment by ateucher** [comment]
New issue opened in #106 to get agreement from contributors
