### ISSUE TITLE
add additional link for inclusion tip

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#103]
Add this as a resource to inclusion tip about "assume good intent"

https://thebias.com/2017/09/26/how-good-intent-undermines-diversity-and-inclusion/
H/T Matt Fisher

**Comment by stefaniebutland** [comment]
[pull request](https://github.com/Openscapes/kyber/pull/104) made. Asked Andy's help for Ubuntu failed R-CMD-check
