### ISSUE TITLE
Change kyber license to MIT

### ISSUE THREAD

**Issue by ateucher** [Openscapes/kyber#106]
We are re-licensing kyber to use the MIT license, to make the license as clear and permissive as possible. To do so, we need the approval of all [contributors](https://github.com/Openscapes/kyber/graphs/contributors)/copyright holders.

@jules32, @seankross, @stefaniebutland, @cclatterbuck, @AHolder1: If you agree to re-license kyber (including your contributions) to the MIT license, please leave a comment below saying "I agree".

Thank you!

- [x] @ateucher 
- [x] @jules32
- [x] @seankross
- [x] @stefaniebutland
- [x] @cclatterbuck
- [x] @AHolder1

**Comment by seankross** [comment]
I agree.

**Comment by stefaniebutland** [comment]
I agree

**Comment by jules32** [comment]
I agree

**Comment by AHolder1** [comment]
I agree

**Comment by cclatterbuck** [comment]
I agree

**Comment by ateucher** [comment]
In case it's not self evident, I also agree 😀
