### ISSUE TITLE
update Call 2 Roll Call - confirm you accept email 

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#122]

**Comment by stefaniebutland** [comment]
so awesome. I just came here to open this issue

**Comment by stefaniebutland** [comment]
- [ ] create `_rollcall_github_username.Rmd` 
- [ ] put in CohortRegistry for Call 2 to replace `_rollcall_something_you_learned.Rmd`

**Comment by stefaniebutland** [comment]
fixed in #126
