### ISSUE TITLE
Agenda 2 - make breakout 1 language consistent with slides

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#124]
Stef did this by hand for NMFS

**Comment by stefaniebutland** [comment]
updating part 2 timing & slide #'s.

- [ ] update slide #'s and timing in Part 1 of GitHub Clinic

**Comment by stefaniebutland** [comment]
fixed in #126

**Comment by stefaniebutland** [comment]
fixed in #126 
moved 2nd checklist item to new issue #129
