### ISSUE TITLE
update/ add Seaside Chat examples in `_closing.Rmd`

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#127]

**Comment by jules32** [comment]
Maybe link to nothing or to https://openscapes.github.io/series/what-to-expect.html#seaside-chats-coworking

**Comment by stefaniebutland** [comment]
I had deleted from `_closing.Rmd`, this prev pointer to older seaside examples:
![Screenshot 2024-11-11 at 11 22 53 AM](https://github.com/user-attachments/assets/97c1f99e-3325-407a-99c1-cd3e9614bace)

**Comment by stefaniebutland** [comment]
closing. decided not to link here
