### ISSUE TITLE
Update slide #'s and timing in Part 1 of GitHub Clinic

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#129]
In 2024-nmfs we added 5-min for video specific to NMFS. We took that time from Julie's part 1. Decide how to list timing in kyber for a less specific cohort lesson

**Comment by stefaniebutland** [comment]
We  had shortened part 1 to accommodate Interlude (Vivian Matter) and Eli's "why GitHub for NMFS" specifically for 2024-nmfs. See Cohort C for that version.
We won't always have these elements so not adding them permanently via kyber.
- [ ] Julie update slides to our current thinking about this lesson
- [ ] Stef update slide numbers in kyber

**Comment by jules32** [comment]
Julie added some monsters and the "here are resources" at the beginning as we've had before.

**Comment by stefaniebutland** [comment]
fixed in #132
