### ISSUE TITLE
Notes/feedback 01_CallAgenda [ 2022-nasa ]

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#14]
Hi @seankross , 

This worked really great! The only additional comment from #13 is the question of images. Call 1 has those 2 screenshots, and when I tried knitting from a random place it returned the following. This might mean I need to call the function from a place with the image (which I ended up doing), and that's great, but I thought I'd share: 

This is what it returned when I tried knitting:

```
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to 'call-1-agenda-2022-nasa_md' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
File openscapes_champions_landscape.png not found in resource path
Error: pandoc document conversion failed with error 99
Execution halted
```

**Comment by seankross** [comment]
Fixed in [6ed286d](https://github.com/Openscapes/kyber/commit/6ed286dfa39b66cdca0ee68f2819845520fee6af)
