### ISSUE TITLE
"bug": date_start at the top of each agenda

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#21]
Hi Sean! 

It looks like each agenda is created with the `date_start` variable from the CohortRegistry instead of incrementing by 2 weeks for each call. I'm not sure we wrote that down anywhere so I wanted to flag it. 

Thank you!

**Comment by stefaniebutland** [comment]
This appears to be resolved. Correct date was added to NASA Call 4 Agenda on May 8.
ok to close issue @seankross ?

**Comment by seankross** [comment]
Good call @stefaniebutland, closing this now.
