### ISSUE TITLE
fix broken link in new cohort README

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#29]
replace link in `[better science in less time](https://openscapes.github.io/series/bsilt)` with 
https://openscapes.github.io/series/better-science.html

https://openscapes.github.io/series/bsilt gives 404

**Comment by jules32** [comment]
yes, this is correct, please make this update

**Comment by stefaniebutland** [comment]
This will need to be changed in kyber, which created the README.

I've manually changed it for current cohort

**Comment by seankross** [comment]
I believe this is changed in the readme in kyber, but I couldn't find the link you were referring to.

**Comment by stefaniebutland** [comment]
ah, I opened this issue when I first used kyber and can't decipher what I meant. Making a couple of agendas March 7th so will check.

**Comment by stefaniebutland** [comment]
Closing the issue. Can't find the link I referred to.
