### ISSUE TITLE
typo in Call 05 closing

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#32]
which file do I update to fix this?

duplicated word "more" in "We hope you feel a bit more confident about what’s possible ..."

**Comment by jules32** [comment]
Good eye - 

First, you can check which file is used for Call 5 Closing in [OpenscapesChampionsCohortRegistry](https://docs.google.com/spreadsheets/d/1Ys9KiTXXmZ_laBoCV2QWEm7AcnGSVQaXvm2xpi4XTSc/edit#gid=942365997) - `call_metadata` tab. This shows it's `_closing_task_final.Rmd`.  

Then you navigate to the file: he .Rmds used to create the Agendas live in the `inst/agendas` folder of this kyber repo. 

Here is the line: https://github.com/Openscapes/kyber/blob/main/inst/agendas/_closing_task_final.Rmd#L10.
