### ISSUE TITLE
Should GitHub Teams have Write access via kyber?

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#43]
Adding team members via kyber gives them `read` access, but they need `write` so I've changed that manually. I *think* they had automatic write access when we set up [sefsc-summer](https://github.com/Openscapes/2022-noaa-sefsc-summer). See read status in screenshot. 

command: `add_team_members(team_name, members = members$username, org = "nmfs-openscapes")`

![Screen Shot 2022-10-14 at 5 38 59 PM](https://user-images.githubusercontent.com/11927811/195961262-3d11593c-8795-4b0d-b46c-213441fc9a09.png)

**Comment by seankross** [comment]
Hey @stefaniebutland, when you add a team to a repository with `add_team_to_repo()` it should give them push access. It looks like it's working properly to me but if it's not working in your workflow then let me know.

**Comment by stefaniebutland** [comment]
I'll test later this week (week of Mar 6) when I add a new team to a Cohort repo

**Comment by stefaniebutland** [comment]
LGTM this time. Closing issue.

<img width="793" alt="Screenshot 2023-03-10 at 6 01 30 PM" src="https://user-images.githubusercontent.com/11927811/224459072-d8e714c3-f9a7-4b82-a1b6-0ea021554d27.png">
