### ISSUE TITLE
Notes on kyber test ... not working yet

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#51]
2023-04-21 installed kyber `remotes::install_github("openscapes/kyber@main")` after Sean merged PR of bug fixes

[Create GitHub repo](https://github.com/openscapes/kyber#create-github-repo):
```
library(kyber) 
library(rmarkdown)
library(tibble)
library(fs)

repo_name <- "stef-test-kyber"

# This will open a README.Rmd for you to edit
repo_path <- init_repo(repo_name)
```
README.Rmd opened successfully = that bug fixed.

Then render the README.Rmd to README.md
```
render(path(repo_path, "README.Rmd"))
```

**error** README.Rmd not found in path, since it had been added to a subdir:
```
> render(path(repo_path, "README.Rmd"))
Error in abs_path(input) : 
  The file '/Users/stefaniebutland/GitHub/openscapes/kyber/README.Rmd' does not exist.
In addition: Warning message:
In normalizePath(x, winslash = winslash, mustWork = must_work) :
  path[1]="/Users/stefaniebutland/GitHub/openscapes/kyber/README.Rmd": No such file or directory
```

![Screenshot 2023-04-21 at 1 08 41 PM](https://user-images.githubusercontent.com/11927811/233725709-17b4ffaa-dbd8-419e-ab8b-52c01d6d9985.png)

Good news from this screenshot; looks like this issue is resolved https://github.com/Openscapes/kyber/issues/48

**error when I manually knit README.Rmd:**
```
  |.....................                               |  40% (setup)          

processing file: README.Rmd
                                                                                                            
Quitting from lines 9-11 (README.Rmd) 
Error in seq.Date(date_start, date_end, by = "2 weeks") : 
  'from' must be of length 1
Calls: <Anonymous> ... eval_with_user_handlers -> eval -> eval -> <Anonymous> -> seq.Date
Execution halted
```

**Comment by stefaniebutland** [comment]
@seankross Ping me here when you'd like me to test anything again.

**Comment by seankross** [comment]
@stefaniebutland whenever you get the chance try this again with the latest version of kyber on the main branch.

**Comment by stefaniebutland** [comment]
@seankross 

```
> repo_path <- init_repo(repo_name)
Looking up https credentials for https://github.com/Openscapes/stef-test2-kyber.git
Transferred 4 of 4 objects...done!
[status] refs/heads/main: unchanged
[new]     cf6a0baabacd203e78d1 refs/remotes/origin/main
```

I added `stef-test4-kyber` to cohort registry and got this error:

```
> render(path(repo_path, "README.Rmd"))
processing file: README.Rmd
  |.........................                                     |  40% (setup)          Quitting from lines 9-11 (README.Rmd) 
**Error** in `kyber:::readme_setup()`:
**! Cohort not found in cohort registry**. Check README.Rmd yaml frontmatter.
Backtrace:
 1. kyber:::readme_setup(params)
```

Also noticed that file `horst-champions-trailhead.png` is not added to the repo and I def want it added when repo is created.

**Comment by seankross** [comment]
> `Cohort not found in cohort registry**. Check README.Rmd yaml frontmatter.`

In the readme's yaml frontmatter:

```
---
params:
  cohort_name: "Cohort"
  cohort_registry: "https://docs.google.com/spreadsheets/d/1Ys9KiTXXmZ_laBoCV2QWEm7AcnGSVQaXvm2xpi4XTSc/"
output: github_document
---
```

Change `cohort_name: "Cohort"` to contain the name of a real cohort like `cohort_name: "2023-nasa-champions"` and then try knitting it again.

**Comment by stefaniebutland** [comment]
aha! thanks. 

Where are  `README.md` and `README.html` created? 
```
Preview created: README.html

Output created: README.md
```

**Comment by seankross** [comment]
Oy, are they not in the same directory as README.Rmd?

**Comment by stefaniebutland** [comment]
just not sure where to find. I wasn't working in a .Rproj
