### ISSUE TITLE
object ‘list_flatten’ error

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#56]
We are running into an error: 

`Error in list_flatten(.) : could not find function "list_flatten"`

<img width="792" alt="image" src="https://github.com/Openscapes/kyber/assets/5891909/0d852c25-ddf4-4d6b-981d-e84c6b2781ad">

That seems to originate from this warning when we `devtools::load_all()`
```
devtools::load_all()
ℹ Loading kyber
Warning message:
object ‘list_flatten’ is not exported by 'namespace:purrr' 
```

Stef and Corey may troubleshoot more but documenting here!

**Comment by seankross** [comment]
Make sure you have the latest version of purrr installed. `list_flatten()` is [exported by purr](https://purrr.tidyverse.org/reference/list_flatten.html) and I can't get this error to happen on my machine.

**Comment by seankross** [comment]
Closing this for now.
