### ISSUE TITLE
Cannot add_team_members to team

### ISSUE THREAD

**Issue by AHolder1** [Openscapes/kyber#59]
Hi! 

I'm having trouble adding individuals to our [2023-swrcb-cohort](https://github.com/orgs/Openscapes/teams/2023-swrcb-cohort) team

We were able to create a team and ran the following code successfully:
```
## create naming for GitHub - do this once!
repo_name <- "2023-swrcb"
team_name <- paste0(repo_name, "-cohort")
create_team(team_name, maintainers = "AHolder1", org = "openscapes")
```
The top of the tribble looks like: 
```
## create member variable - do this twice (first as test!)
## this is where you'll use datapasta and run everything below
members <- tibble::tribble(
                      ~username,
                           "tures23",
                           "DevanBurke", 
                           ...
)
```

The errors I get are
![image](https://github.com/Openscapes/kyber/assets/49571531/357866ea-9753-4549-addf-cf6caef0b313)

**Comment by stefaniebutland** [comment]
@AHolder1 Awesome analogies during team creation screenshare via kyber and datapasta! 

🤔 you successfully added a few folks to the team in your first run, so maybe adding additional folks in a new session will work.

I was able to add a new member to the team though GitHub browser (screenshot shows 1 pending member; same user you tried to add) using same method that did not work for you. Could you re-login to GitHub browser and add someone else manually, then if successful retry via kyber? 

![Screenshot 2023-08-07 at 4 07 10 PM](https://github.com/Openscapes/kyber/assets/11927811/cb5e6249-a196-41e9-9d17-d5359c9d383d)

If you tag me here, I'll get email notification and respond asap.

**Comment by cclatterbuck** [comment]
Perhaps the error is because Anna is a maintainer and not admin? I believe errors like this are why Kyber suggests the admin:org scope in the PAT. [GitHub roles](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization)

**Comment by stefaniebutland** [comment]
For 2022-swrcb-cohort team, Corey and Anna had maintainer permission, while you have Admin privileges for the repo, so this *should* be ok. Happy to help resolve this

**Comment by stefaniebutland** [comment]
aahh, realizing Corey prob means GitHub PAT scope, not the Admin permission I was referring to. Following up with Anna

**Comment by AHolder1** [comment]
@stefaniebutland I ran the code and got:
`• Token scopes: 'gist, repo, workflow'
`

I looked at my PAT and it includes: 
`admin:enterprise, admin:gpg_key, admin:org, admin:org_hook, admin:public_key, admin:repo_hook, admin:ssh_signing_key, audit_log, codespace, delete:packages, delete_repo, gist, notifications, project, repo, user, workflow, write:discussion, write:packages`


But there is also a note that my PAT has never been used - so maybe I don't have things connected correctly?? I'm looking into this now.

**Comment by stefaniebutland** [comment]
@AHolder1 I'm free till 9:55am PT if you want to screenshare (no obligation)

I think your token scopes could be the problem. [kyber README](https://github.com/openscapes/kyber#example-workflow) says You can create your PAT with `usethis::create_github_token()` **with their defaults, plus admin:org**

**Comment by AHolder1** [comment]
I was able to update my PAT and get: 
`• Token scopes: 'admin:org, gist, repo, user, workflow'
`

However, when I re-ran the instructions to add members to the team I got: 
![image](https://github.com/Openscapes/kyber/assets/49571531/c8295318-c4b3-45dd-9c79-be7fb082b4dc)


Fortunately, @stefaniebutland was able to add the members for me. Thank you! :)

**Comment by stefaniebutland** [comment]
Permissions for 2023-swrcb

![Screenshot 2023-08-31 at 9 39 28 AM](https://github.com/Openscapes/kyber/assets/11927811/be997e74-cacd-412f-8259-95d36e17dc4d)

**Comment by stefaniebutland** [comment]
Anna is Maintainer for Team

![Screenshot 2023-08-31 at 9 40 22 AM](https://github.com/Openscapes/kyber/assets/11927811/c21c89bf-4e05-4059-853d-afc8fcdc76ac)

**Comment by stefaniebutland** [comment]
@jules32 Can you see something we're missing here? @AHolder1 was not able to add members to team, either via kyber OR GitHub web interface. I was able to add them both ways.

![Screenshot 2023-08-31 at 9 43 54 AM](https://github.com/Openscapes/kyber/assets/11927811/58a6f13c-af2d-490f-82de-3b3ddcd6a863)

**Comment by jules32** [comment]
Hmm yes I don't see anything here that wouldn't let @AHolder1 make teams. Thanks @stefaniebutland for helping, this is something we can work on further with kyber to fix hopefully

**Comment by seankross** [comment]
Thank you all for constructing such a detailed issue! I will try my best to get around to this early next week.

**Comment by seankross** [comment]
For the life of me I can't reproduce this. @AHolder1 are you still having this issue?

**Comment by stefaniebutland** [comment]
It's been a long time since we tried. @AHolder1 and I will report back when we cowork to do this for their March cohort

**Comment by seankross** [comment]
@stefaniebutland would you be open to me joining you for part of that coworking? It would be great to debug live if possible.

**Comment by stefaniebutland** [comment]
absolutely! nothing scheduled yet.

**Comment by stefaniebutland** [comment]
> would you be open to me joining you for part of that coworking? It would be great to debug live if possible.

@seankross Anna and I are coworking Fri Feb 9, 9 - 11 am PT. Could you join us for part of that? We'll mainly be making agendas from new Rmd content

**Comment by seankross** [comment]
Unfortunately I can't make it Friday. If you're coworking virtually, would you be willing to record it?

**Comment by stefaniebutland** [comment]
Resolved!!!... by itself 🤷🏼‍♀️
