### ISSUE TITLE
kyber: Call 1 add red notes: (pause recording)

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#63]
See Fred Hutch Call 1 (and maybe additional calls)

**Comment by jules32** [comment]
Started this here: https://github.com/Openscapes/kyber/commit/504c7e4840f656c93672ab80a5bf158469d87b01

**Comment by stefaniebutland** [comment]
formatting to add
`(<font color="red">pause recording</font>)`
`(<font color="red">start recording</font>)`

**Comment by stefaniebutland** [comment]
I didn't add pause / restart recording when we had only 5-mins of silent journaling

**Comment by stefaniebutland** [comment]
fixed (I think) with https://github.com/Openscapes/kyber/pull/64

We'll see when we create next set of agendas.
