### ISSUE TITLE
Update mindset slides link

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#65]
updated link: https://docs.google.com/presentation/d/1fXgrWU5AMrZwgvpjs2J0dRT9x1Tc-IZyQIn8yPZSGM8/edit?usp=sharing

**Comment by jules32** [comment]
switch goals with organizer welcome

**Comment by jules32** [comment]
"Honor and awe" - Liz Neeley

**Comment by stefaniebutland** [comment]
mindset slides link updated in 962bae3effabd5e5e0da57fdf40f839d16425d39
