### ISSUE TITLE
Give @AHolder1 access to contribute to dev?

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#83]
Hi @seankross 

Working with @AHolder1  to create new Rmds for CA Water Boards. What workflow do you suggest she use?
Anna does not have the permissions option to Contribute that I have.

![Screenshot 2024-01-18 at 10 47 53 AM](https://github.com/Openscapes/kyber/assets/11927811/829c030c-cfa0-4086-b721-debece633b31)

Should she clone kyber, and make a new branch off of `dev`? And then make pull request to dev? (question comes from some GitHub naivety on my part)

**Comment by stefaniebutland** [comment]
for now, I'll do the contributing

**Comment by seankross** [comment]
Hi Steph,

My preference would be that she fork Kyber, start working from off of the `dev` branch, and then submit PRs to `dev`. Does that work? When forking kyber she needs to uncheck the "Copy the main branch only" box. If she's using git on the command line her workflow would look like:

- clone your fork of kyber
- `git checkout -b dev`
- `git pull origin dev`
- to start working on a new branch off of dev: `git checkout -b new-branch dev`

**Comment by stefaniebutland** [comment]
Got it! Thanks for quick response!

And I'll start using the same workflow, making PRs to `dev`. I had been pushing to main 🤦🏼‍♀️

**Comment by seankross** [comment]
Don't worry about it! It will all come out in the wash.

**Comment by stefaniebutland** [comment]
Stef to document this then close

**Comment by stefaniebutland** [comment]
done: https://github.com/Openscapes/kyber/blob/main/README.md#contributing-to-kyber
