### ISSUE TITLE
create README.Rmd independently of creating cohort repo

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#85]
When co-working with @AHolder1, she successfully followed Kyber instructions to create a repo. But after an error creating the README.Rmd (screenshot; we forgot to replace YAML `Cohort` with actual cohort name), neither of us was able to create the Rmd after the new repo already existed. Can we have a separate Kyber cmd to create the Cohort README.Rmd after the new repo exists?

```
repo_name <- "2024-swrcb-spring"
repo_path <- init_repo(repo_name)
render(path(repo_path, "README.Rmd"))
```

Anna’s error when trying to generate the README.Rmd:

![Screenshot 2024-02-09 at 11 58 05 AM](https://github.com/Openscapes/kyber/assets/11927811/a977e3b8-2fa6-4cc7-8cb9-a18b1dcd45fd)

When Stef tried to create the README.Rmd after Anna had created repo. She got this error:  

```
> repo_path <- init_repo(repo_name)
Error: A GitHub repository named 2024-swrcb-spring already exists for the openscapes organization.
```

**Comment by stefaniebutland** [comment]
Hi @seankross. I'll be using kyber heavily soon - Sep 23 or sooner if possible - to make Cohort repos and agendas. Will you have time to address some issues? If not, ok; kyber still rocks to do what we need!

**Comment by seankross** [comment]
@stefaniebutland I think the original issue that Anna ran into is fixed, whereas your issue:

```r
repo_name <- "2024-swrcb-spring"
repo_path <- init_repo(repo_name)
#> Error: A GitHub repository named 2024-swrcb-spring already exists for the openscapes organization.
```

Is the correct behavior since you shouldn't be able to initialize the same repo on GitHub if it already exists.

---

Regardless, you should be able to create a readme independently of creating a repo with: `kyber::create_readme()`, which is called by `init_repo()`. Am I missing something here?

**Comment by stefaniebutland** [comment]
Thanks @seankross, yes `kyber::create_readme()` was the command we needed!
