### ISSUE TITLE
Notes/feedback from Call 3 Agenda

### ISSUE THREAD

**Issue by jules32** [Openscapes/kyber#9]
Hi @seankross ! Thanks so much for making the Call 3 agenda! 

I've gone through to prepare for Friday and have documented my process here for our information. Summary: it is so great! Thank you!

I've also made some small updates to the .Rmds during my review (my text and spacing, etc). https://github.com/Openscapes/kyber/pull/8. 

## Julie Notes

Sean provided call-3-2022-noaa-afsc.md (attached here for our records). 
[call-3-2022-noaa-afsc.md](https://github.com/Openscapes/kyber/files/8024457/call-3-2022-noaa-afsc.md)

- I knitted it in RStudio, pasted it into a Google Doc: 03_CallAgenda [ 2022-noaa-afsc ], and made the following edits in the doc
- Changed font to Open Sans - full doc
- Made "_opening.Rmd" part 9 point font (specific to Call 3 Agenda)
- Made Header 1 font 18, bold ; update heading 1 to match (see screenshot below)
- Made Header 2 font 14, bold; update heading 2 to match
- Select all then: 
  - "add space" then "remove space **after** paragraph" throughout to make spacing a little more cozy
  -  "add space" then "remove space **before** paragraph" throughout to make spacing a little more cozy
- Went through and any further font weirdness I revisited in the .Rmds (added the invisible space in a few places in the bulleted lists) - see commit/PR above
- I added page numbers 

**Explanation of "update heading 1 to match"**
In Google Doc, to update a text style (headings, normal text, with font type, size etc), highlight a section of the style you want, click the styles dropdown shown in the screenshot, and select e.g. "Update Heading 1 to match". Double check the doc because we've noticed it missed some in an agenda.

![Screen Shot 2022-07-14 at 5 50 28 PM](https://user-images.githubusercontent.com/11927811/179125336-ec2fc1e5-792e-495d-8a29-c1ed3ec3cdc4.png)

**Comment by stefaniebutland** [comment]
Moved these notes to README

**Comment by stefaniebutland** [comment]
Closing. Info now in README
