### ISSUE TITLE
Merge Kyber dev into main

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#92]
Opening issue for your awareness @seankross. We're keen to merge Kyber [dev](https://github.com/Openscapes/kyber/tree/dev&sa=D&source=calendar&ust=1713887531809758&usg=AOvVaw2tSh86pxwpT0nk9wbciYf6) to main. I hope this is ok Sean! We're using Kyber a lot more now, as well as expanding how we use it. Creating Certificates for completion of programs and custom Agendas for California Water Boards (this is so awesome). And I'm doing a Posit conf lightning talk about this in August. 

Friday Apr 19 9am @ateucher will help me merge dev into main, get `create_certificate` Rmd and R script into Main and we'll get into a clean workflow for future contributions via dev. 

Also awesome is that Andy has joined the Openscapes team primarily to support our NASA Earthdata Cloud work 🚀 .

**Comment by seankross** [comment]
@stefaniebutland sounds good to me. I opened a PR here: https://github.com/Openscapes/kyber/pull/93.

**Comment by ateucher** [comment]
Closed by #93
