### ISSUE TITLE
Fix website build and deploy

### ISSUE THREAD

**Issue by ateucher** [Openscapes/kyber#95]
Because previously there was no action to deploy the website, we all have out of date local copies of the `docs/` folder. We should have the website only render via actions, probably on `gh-pages` branch, and remove the `docs/` folder from main.

**Comment by ateucher** [comment]
@seankross I would like to remove the `docs/` folder and deploy the site from `gh-pages` branch, using [this action](https://github.com/r-lib/actions/blob/v2-branch/examples/pkgdown.yaml). This will make the rendered site only exist in the `gh-pages` branch and prevent the rendered `docs/` folder from cluttering up our git history/cause merge conflicts. What do you think?

**Comment by seankross** [comment]
go for it!

**Comment by stefaniebutland** [comment]
@ateucher pls tag me when you've done this. Thanks

**Comment by ateucher** [comment]
@stefaniebutland @seankross @jules32 this is done! The rendered pkgdown site now only lives in the `gh-pages` branch, and the repo is configured to serve the site from there. It will _build_ the site on PRs (but not deploy), and _deploy_ when PRs are merged to main or you push directly to main. No more rendered `docs/` in git (I deleted the folder and added it to `.gitignore`).

**Comment by ateucher** [comment]
If you have any local branches, please pull and merge main into them so you don't accidentally re-commit `docs/`

**Comment by stefaniebutland** [comment]
@ateucher I'm a novice at "please pull and merge main into" a branch.
I want to merge this pull request: https://github.com/Openscapes/kyber/pull/71 that's on an old branch https://github.com/Openscapes/kyber/tree/cert-completion

Can you please give me an explicit line or to to do this? Or a ~15min screenshare zoom so I can drive?

**Comment by ateucher** [comment]
Yes, sorry to be obtuse!

If you want to stay in R land, the [PR Helpers](https://usethis.r-lib.org/articles/pr-functions.html) are really nice. Using that at the R console, you would do:

```r
library(usethis)

pr_fetch(71) # checks out the branch and pulls it down locally
pr_merge_main() # pulls main and merges it into your current branch
pr_push() # pushes your current branch/PR
```

If you want to do it in the terminal, the steps would be:

1. make sure you have all the updates to main locally:

```
git checkout main
git pull
```

2. make sure you have all updates to cert-completion locally

```
git checkout cert-completion
git pull
```

3. merge main into cert-completion and push to GitHub, updating the PR

```
git merge main
git push
```

**Comment by ateucher** [comment]
I think we can close this now @stefaniebutland?

**Comment by stefaniebutland** [comment]
Thank you both so much!
