### ISSUE TITLE
Khora Image not inserted in Call 5 agenda

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/kyber#97]
source https://github.com/Openscapes/kyber/blob/main/inst/agendas/_closing_task_final.Rmd

I thought this was fixed in PR #96. That PR fixed image to appear in Call 3, but not this one. I'm stumped for now

**Comment by stefaniebutland** [comment]
@seankross can you please help with this?

**Comment by seankross** [comment]
I can't reproduce this issue (on `main`). Here is the code I ran where it works for me:

```
library(kyber) 

registry_url = "you know the url"
cohort_id = "2024-noaa-a"
call_number = 5

call_agenda(registry_url = registry_url, 
            cohort_id = cohort_id, 
            call_number = call_number)

rmarkdown::render("agenda.md", output_format = rmarkdown::html_document()) |> 
  browseURL()
```

**Comment by stefaniebutland** [comment]
Thanks Sean. Worked for me this time. Closing.
